name = "FedEx Shipping Rate Provider"
client_id = "c46d4b4823103eb7f599c58749caaf89"
type = "app"

# URL onde seu app est√° hospedado (por enquanto localhost)
scopes = "write_shipping,read_shipping"

[[extensions]]
type = "shipping_rate_definition"
handle = "fedex-shipping-rates"
